// Witty rotating status lines, news/investigation flavored. Shown while the
// agent discovers sources or collects articles.

export const DISCOVER_PHRASES = [
  "Looking for the truth…",
  "Checking billions of sources…",
  "Chasing down leads…",
  "Following the paper trail…",
  "Shaking the internet for feeds…",
  "Interrogating the search results…",
  "Reading between the headlines…",
  "Knocking on RSS doors…",
  "Sniffing out hidden feeds…",
  "Cross-examining the web…",
  "Tailing the sources…",
  "Digging through the archives…",
  "Vetting the usual suspects…",
  "Auditioning news sources…",
  "Separating signal from noise…",
  "Wrangling unruly RSS feeds…",
  "Asking the internet to cite its sources…",
  "Hunting for primary sources…",
  "Casing the newsstands…",
  "Triangulating the story…",
  "Calling in favors from search engines…",
  "Pulling threads…",
  "Reading the fine print…",
  "Eavesdropping on the wire…",
  "Following the money…",
  "Connecting the dots…",
  "Cracking open the feed readers…",
  "Mapping the media landscape…",
  "Negotiating with paywalls…",
  "Befriending the algorithm…",
  "Scouring the back pages…",
  "Tracing rumors to their roots…",
  "Compiling a watchlist…",
  "Hunting for hidden gems…",
  "Tuning the antenna…",
  "Checking with our sources…",
  "Reading tea leaves and RSS…",
  "Chasing the next big story…",
  "Stress-testing credibility…",
  "Counting reputable outlets…",
  "Pinging far-flung servers…",
  "Down a hyperlink rabbit hole…",
  "Decoding feed formats…",
  "Sorting the credible from the clickbait…",
  "Asking around the newsroom…",
  "Scanning the horizon…",
  "Rounding up the candidates…",
  "Sizing up the competition…",
  "Reading everything, twice…",
  "Sniffing for scoops…",
  "Subpoenaing the search results…",
  "Polishing the magnifying glass…",
  "Looking under every rock…",
  "Consulting the oracle (it's just Brave)…",
  "Sweet-talking the servers…",
  "Verifying, then verifying again…",
  "Doing actual journalism, allegedly…",
  "Untangling the web…",
  "Cornering reliable narrators…",
  "Filtering out the noise…",
];

export const COLLECT_PHRASES = [
  "Rounding up the headlines…",
  "Fetching the latest…",
  "Skimming the front pages…",
  "Reeling in articles…",
  "Catching up on the news…",
  "Sorting fresh from stale…",
  "Filing the stories…",
  "De-duplicating the chatter…",
  "Reading the morning papers…",
  "Collecting the day's drama…",
  "Stacking up stories…",
  "Pulling the latest dispatches…",
  "Refreshing the feeds…",
  "Gathering intel…",
  "Indexing the news…",
  "Catching the wire…",
  "Scooping up scoops…",
  "Loading the briefing…",
  "Counting bylines…",
  "Filtering the firehose…",
  "Wrangling the day's news…",
  "Stamping the timestamps…",
  "Bringing it all home…",
];
